export const NAME_TO_ISO = {
  ESPAÑA: "ES",
  ITALIA: "IT",
  "ESTADOS UNIDOS": "US",
  CANADA: "CA",
  CANADÁ: "CA",
  VENEZUELA: "VE",
  COLOMBIA: "CO",
  PERU: "PE",
  PERÚ: "PE",
  CHILE: "CL",
  ARGENTINA: "AR",
  BRASIL: "BR",
  MEXICO: "MX",
  MÉXICO: "MX",
  RUSIA: "RU",
  CHINA: "CN",
  JAPON: "JP",
  JAPÓN: "JP",
  AUSTRALIA: "AU",
  "REINO UNIDO": "GB",
  FRANCIA: "FR",
  ALEMANIA: "DE",
  SUIZA: "CH",
  BELGICA: "BE",
  BÉLGICA: "BE",
  "PAISES BAJOS": "NL",
  SUECIA: "SE",
};
